### PR TITLE
fixed cc err when not adding with-stream_ssl_module

### PR DESCRIPTION
**Pull request by vislee**

### CODE REVIEW

**Comment by vislee** [comment]
@thibaultcha 

The `‘conf’ undeclared` when not adding `--with-stream_ssl_module`
```sh
/home/travis/build/vislee/stream-lua-nginx-module/src/ngx_stream_lua_module.c: In function ‘ngx_stream_lua_merge_srv_conf’:
/home/travis/build/vislee/stream-lua-nginx-module/src/ngx_stream_lua_module.c:861:26: error: ‘conf’ undeclared (first use in this function)
```
[detail](https://travis-ci.org/vislee/lua-resty-dns-server/jobs/607029608#L2044)

**Comment by vislee** [comment]
@agentzh   Can you review, Is a bug?

**Comment by Pablohn26** [comment]
> 

I can confirm I hit [this](https://github.com/openresty/stream-lua-nginx-module/pull/179#issuecomment-549645790) compiling error when compiling without `--with-stream_ssl_module`

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
merged

**Pull request closed without merging**
