### PR TITLE
Fix compilation against NgX-1.11.4; fixes #40

### LINKED ISSUE #40: Broken compilation against NginX-1.11.4
```make
.../nginx-1.11.4/work/stream-lua-nginx-module-aafd50b2e03fb36a88c2aff81d883d985dcc517f/src/ngx_stream_lua_util.c: In function 'ngx_stream_lua_free_session':
.../nginx-1.11.4/work/stream-lua-nginx-module-aafd50b2e03fb36a88c2aff81d883d985dcc517f/src/ngx_stream_lua_util.c:3206:9: warning: implicit declaration of function 'ngx_stream_close_connection' [-Wimplicit-function-declaration]
         ngx_stream_close_connection(s->connection);
         ^
configuring for Linux 4.7.2 x86_64
checking for C compiler: x86_64-pc-linux-gnu-gcc
 + using GNU C compiler
 + gcc version 5.4.0 (Gentoo 5.4.0 p1.0, pie-0.6.5)
<...>
 + PCRE version: 8.39
cp nginx.pm blib/lib/nginx.pm
Running Mkbootstrap for nginx ()
Manifying 1 pod document
objs/addon/src/ngx_stream_lua_util.o: In function `ngx_stream_lua_free_session':
ngx_stream_lua_util.c:(.text+0x28fc): undefined reference to `ngx_stream_close_connection'
ngx_stream_lua_util.c:(.text+0x2905): undefined reference to `ngx_stream_close_connection'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:676: objs/nginx] Error 1
make: *** [Makefile:8: build] Error 2
```

### PR DESCRIPTION
**Pull request by msva**
Here is PR, as suggested by @agentzh in #40

### CODE REVIEW

**Comment by msva** [comment]
as far as I can see, travis build failure is not because of commit

**Comment by msva** [comment]
ping?

**Comment by agentzh** [comment]
@msva Been busy. Will get back to you when I have some more time. Sorry for the delay on my side.

**Comment by dndx** [comment]
No longer needed. We don't plan on supporting old NGINX anymore.

**Pull request closed without merging**
